# 配置地址
ipAddress: 192.168.1.128
server:
  port: 8080
spring:
  application:
    name: server-messages
  datasource:
    url: jdbc:mysql://localhost:3306/message_db
    username: root
    password: 123456
  redis:
    host: ${ipAddress}
    port: 6379
    password: 990416
    database: 0

mybatis-plus:
  #  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.codeking.serverMessage.entity
  configuration:
    map-underscore-to-camel-case: true

# XXL-Job配置
#xxl:
#  job:
#    admin:
#      addresses: http://localhost:8160/xxl-job-admin
#    executor:
#      address:
#      # 注册名字
#      appname: my-job-executor
#      port: 9999
#    accessToken: "default_token"
